### ISSUE TITLE
matchbox Irrational recipes

### ISSUE THREAD

**Issue by al-wei** [Noble772/RealisticTorchesRoA-1.12.2#1]
`{
  "result": {
    "item": "realistictorches:matchbox"
  },
  "ingredients": [
    {
      "item": "realistictorches:matchbox"
    },
    {
      "item": "realistictorches:matchbox"
    }
  ],
  "type": "minecraft:crafting_shapeless"
}`

I've always noticed that two complete matchboxes make a matchbox. What's the point.
![image](https://github.com/user-attachments/assets/958f4c18-2815-4811-9970-4124be2ada23)
In fact, it amounts to cheating. Let the player get the third matchbox.

**Comment by al-wei** [comment]
This problem is also in Realistic Torches.

**Comment by al-wei** [comment]
I think it was originally designed to simulate two broken tools making a better tool.
But obviously this is wrong. It should be fixed, or deleted.

**Comment by Noble772** [comment]
This mod is for my modpack so I'm not going to be fixing any bugs since I've already removed those recipes with crafttweaker in my own pack. If you or anyone wishes to do bug fixes on the mod then feel free to fork.
